/**
 *
 * $Id$
 */
package org.eclipse.actor.oriented.validation;

import org.eclipse.actor.oriented.Component;
import org.eclipse.actor.oriented.Port;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.actor.oriented.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateInputComponetRefs(EList<Component> value);
	boolean validateOutputComponetRefs(EList<Component> value);
	boolean validateInputPortRefs(EList<Port> value);
	boolean validateOutputPortRefs(EList<Port> value);
	boolean validateId(String value);
	boolean validateInputCnt(int value);
	boolean validateOutputCnt(int value);
}
